services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_MODEL=tinyllama  # Default model (small enough to run for most users)

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - /home/juliane/.ollama:/root/.ollama
